const API_BASE_URL = 'http://localhost:8000';

/**
 * Retrieve a list of all active or saved conversation threads.
 * @returns {Promise<Array>} List of conversation objects
 */
export async function getConversations() {
  const response = await fetch(`${API_BASE_URL}/api/conversations`);
  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.detail || 'Failed to fetch conversations');
  }
  return response.json();
}

/**
 * Fetch the complete chronological chat log for a given thread.
 * @param {string} threadId - Unique conversation ID
 * @returns {Promise<Array>} List of chat message objects
 */
export async function getHistory(threadId) {
  const response = await fetch(`${API_BASE_URL}/api/conversations/${threadId}/history`);
  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.detail || 'Failed to fetch chat history');
  }
  return response.json();
}

/**
 * Send a chat message to the assistant.
 * @param {string} message - User query text
 * @param {string|null} threadId - Thread ID context (new UUID will be generated by backend if null)
 * @param {string|null} modelName - LLM variant name (e.g. gemini-2.5-flash)
 * @returns {Promise<object>} Response with agent text and thread_id
 */
export async function sendMessage(message, threadId = null, modelName = null) {
  const response = await fetch(`${API_BASE_URL}/api/chat`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      message,
      thread_id: threadId,
      model_name: modelName,
    }),
  });
  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.detail || 'Failed to send message');
  }
  return response.json();
}

/**
 * Upload a document and index its content for RAG search.
 * @param {File} file - The file to upload
 * @param {string} threadId - Thread ID context to bind the file scope to
 * @returns {Promise<object>} Status, filename, and thread_id details
 */
export async function uploadFile(file, threadId) {
  const formData = new FormData();
  formData.append('file', file);
  formData.append('thread_id', threadId);

  const response = await fetch(`${API_BASE_URL}/api/upload`, {
    method: 'POST',
    body: formData,
  });
  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.detail || 'Failed to upload file');
  }
  return response.json();
}
